version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"  # Usa la versión correcta de Python
sphinx:
  configuration: docs/conf.py  # Ruta a tu archivo conf.py
python:
  install:
    - requirements: requirements.txt  # Instalar dependencias desde requirements.txt
