version: 2
python:
  version: 3.8  # Ajusta según la versión de Python que necesitas
  install:
    - requirements: binder/requirements.txt  # Ruta a tu archivo requirements.txt

build:
  os: ubuntu-20.04  # O usa otro valor como 'ubuntu-22.04'
  tools:
    - jupyter-book  # Usamos Jupyter Book para construir el proyecto
