version: 2
python:
  version: 3.8  # Ajusta según la versión de Python que necesitas
  install:
    - requirements: binder/requirements.txt  # Ruta a tu archivo requirements.txt

build:
  tools:
    - jupyter-book  # Esto le indica a Read the Docs que use Jupyter Book para construir el proyecto
