version: 2
python:
  version: 3.8  # Ajusta según la versión de Python que necesitas
  install:
    - requirements: binder/requirements.txt  # Ruta a tu archivo requirements.txt

build:
  tools:
    jupyter-book:  # El nombre de la herramienta, como un diccionario
      version: 0.11  # Versión de la herramienta (opcional)
