version: 2
build:
  os: ubuntu-20.04  # Sistema operativo utilizado para la construcción
  tools:
    python: "3.8"  # Versión de Python que deseas usar para la construcción
sphinx:
  configuration: docs/conf.py  # Ruta al archivo conf.py de Sphinx (ajusta si es necesario)
python:
  install:
    - requirements: requirements.txt  # Instalar dependencias desde requirements.txt en la raíz
